import { LearningModule } from '../App';

export const mockModules: LearningModule[] = [
  {
    id: 'mod-001',
    title: 'React Advanced Patterns',
    description: 'Master advanced React patterns including compound components, render props, and custom hooks',
    type: 'video',
    duration: 45,
    difficulty: 'advanced',
    category: 'Frontend Development',
    mandatory: false,
    progress: 65,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    tags: ['React', 'JavaScript', 'Frontend'],
    createdBy: 'emp-001',
  },
  {
    id: 'mod-002',
    title: 'Security Compliance Training 2024',
    description: 'Annual security and compliance training required for all employees',
    type: 'interactive',
    duration: 30,
    difficulty: 'beginner',
    category: 'Compliance',
    mandatory: true,
    progress: 100,
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400',
    tags: ['Security', 'Compliance', 'Mandatory'],
  },
  {
    id: 'mod-003',
    title: 'Microservices Architecture Deep Dive',
    description: 'Learn how to design, build, and deploy scalable microservices',
    type: 'podcast',
    duration: 60,
    difficulty: 'intermediate',
    category: 'Backend Development',
    mandatory: false,
    progress: 20,
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
    tags: ['Architecture', 'Backend', 'Microservices'],
  },
  {
    id: 'mod-004',
    title: 'Data Privacy & GDPR',
    description: 'Understanding data privacy regulations and GDPR compliance',
    type: 'document',
    duration: 40,
    difficulty: 'beginner',
    category: 'Compliance',
    mandatory: true,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400',
    tags: ['Privacy', 'GDPR', 'Compliance'],
  },
  {
    id: 'mod-005',
    title: 'Leadership Fundamentals',
    description: 'Essential leadership skills for aspiring managers and team leads',
    type: 'video',
    duration: 90,
    difficulty: 'intermediate',
    category: 'Leadership',
    mandatory: false,
    progress: 40,
    thumbnail: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Leadership', 'Management', 'Soft Skills'],
  },
  {
    id: 'mod-006',
    title: 'TypeScript Mastery',
    description: 'From basics to advanced TypeScript features and patterns',
    type: 'video',
    duration: 120,
    difficulty: 'intermediate',
    category: 'Frontend Development',
    mandatory: false,
    progress: 15,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400',
    tags: ['TypeScript', 'JavaScript', 'Frontend'],
  },
  {
    id: 'mod-007',
    title: 'Agile & Scrum Best Practices',
    description: 'Master agile methodologies and scrum framework',
    type: 'podcast',
    duration: 50,
    difficulty: 'beginner',
    category: 'Project Management',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    tags: ['Agile', 'Scrum', 'Project Management'],
  },
  {
    id: 'mod-008',
    title: 'Cloud Architecture with AWS',
    description: 'Design and implement scalable cloud solutions on AWS',
    type: 'video',
    duration: 180,
    difficulty: 'advanced',
    category: 'Cloud Computing',
    mandatory: false,
    progress: 5,
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    tags: ['AWS', 'Cloud', 'Architecture'],
  },
  {
    id: 'mod-009',
    title: 'Kubernetes Essentials',
    description: 'Manage containers at scale with Kubernetes fundamentals',
    type: 'video',
    duration: 75,
    difficulty: 'intermediate',
    category: 'DevOps',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Kubernetes', 'Containers', 'DevOps'],
    popularityScore: 78,
  },
  {
    id: 'mod-010',
    title: 'Docker Deep Dive',
    description: 'Build, ship, and run applications with Docker',
    type: 'video',
    duration: 60,
    difficulty: 'beginner',
    category: 'DevOps',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Docker', 'Containers'],
    popularityScore: 70,
  },
  {
    id: 'mod-011',
    title: 'Node.js Performance Tuning',
    description: 'Optimize Node.js apps for speed and scalability',
    type: 'podcast',
    duration: 45,
    difficulty: 'intermediate',
    category: 'Backend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Node.js', 'Performance'],
    popularityScore: 64,
  },
  {
    id: 'mod-012',
    title: 'React Testing Library in Practice',
    description: 'Confidently test React components with RTL',
    type: 'document',
    duration: 50,
    difficulty: 'intermediate',
    category: 'Frontend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=250&fit=crop&crop=entropy',
    tags: ['React', 'Testing'],
    popularityScore: 72,
  },
  {
    id: 'mod-013',
    title: 'Advanced TypeScript Patterns',
    description: 'Utility types, generics, and advanced typing techniques',
    type: 'video',
    duration: 95,
    difficulty: 'advanced',
    category: 'Frontend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=250&fit=crop&crop=entropy',
    tags: ['TypeScript', 'Patterns'],
    popularityScore: 85,
  },
  {
    id: 'mod-014',
    title: 'Design Thinking Foundations',
    description: 'Human-centered approach to problem solving',
    type: 'document',
    duration: 40,
    difficulty: 'beginner',
    category: 'UI/UX',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1532619187608-e5375cab36aa?w=400&h=250&fit=crop&crop=entropy',
    tags: ['UX', 'Design'],
    popularityScore: 60,
  },
  {
    id: 'mod-015',
    title: 'Figma for Developers',
    description: 'Collaborate effectively with designers in Figma',
    type: 'video',
    duration: 55,
    difficulty: 'beginner',
    category: 'UI/UX',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Figma', 'Collaboration'],
    popularityScore: 62,
  },
  {
    id: 'mod-016',
    title: 'Python for Data Analysis',
    description: 'Pandas, NumPy, and data wrangling essentials',
    type: 'video',
    duration: 110,
    difficulty: 'intermediate',
    category: 'Data Science',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Python', 'Data'],
    popularityScore: 88,
  },
  {
    id: 'mod-017',
    title: 'Intro to Machine Learning',
    description: 'Supervised vs unsupervised learning and pipelines',
    type: 'video',
    duration: 100,
    difficulty: 'beginner',
    category: 'Data Science',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981d?w=400&h=250&fit=crop&crop=entropy',
    tags: ['ML', 'AI'],
    popularityScore: 90,
  },
  {
    id: 'mod-018',
    title: 'Cloud Cost Optimization',
    description: 'Reduce cloud spend without sacrificing performance',
    type: 'podcast',
    duration: 35,
    difficulty: 'intermediate',
    category: 'Cloud Computing',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Cloud', 'FinOps'],
    popularityScore: 67,
  },
  {
    id: 'mod-019',
    title: 'CI/CD with GitHub Actions',
    description: 'Automate builds, tests, and deployments',
    type: 'video',
    duration: 80,
    difficulty: 'intermediate',
    category: 'DevOps',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=400&h=250&fit=crop&crop=entropy',
    tags: ['CI/CD', 'GitHub'],
    popularityScore: 75,
  },
  {
    id: 'mod-020',
    title: 'Web Accessibility Essentials',
    description: 'Build inclusive experiences with a11y best practices',
    type: 'document',
    duration: 45,
    difficulty: 'beginner',
    category: 'Frontend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Accessibility', 'WCAG'],
    popularityScore: 68,
  },
  {
    id: 'mod-021',
    title: 'Micro Frontends Architecture',
    description: 'Decompose large apps into independently deployable parts',
    type: 'video',
    duration: 85,
    difficulty: 'advanced',
    category: 'Architecture',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Micro Frontends', 'Architecture'],
    popularityScore: 73,
  },
  {
    id: 'mod-022',
    title: 'Secure Coding in JavaScript',
    description: 'Avoid common vulnerabilities and secure your code',
    type: 'document',
    duration: 50,
    difficulty: 'intermediate',
    category: 'Security',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Security', 'JavaScript'],
    popularityScore: 82,
  },
  {
    id: 'mod-023',
    title: 'PostgreSQL Performance',
    description: 'Indexes, query plans, and tuning strategies',
    type: 'video',
    duration: 70,
    difficulty: 'intermediate',
    category: 'Databases',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Postgres', 'SQL'],
    popularityScore: 69,
  },
  {
    id: 'mod-024',
    title: 'API Design with OpenAPI',
    description: 'Design-first APIs with clear contracts',
    type: 'video',
    duration: 65,
    difficulty: 'beginner',
    category: 'Backend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=400&h=250&fit=crop&crop=entropy',
    tags: ['API', 'OpenAPI'],
    popularityScore: 71,
  },
  {
    id: 'mod-025',
    title: 'Observability: Logs, Metrics, Traces',
    description: 'Instrument and observe distributed systems',
    type: 'podcast',
    duration: 50,
    difficulty: 'intermediate',
    category: 'DevOps',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1532619187608-e5375cab36aa?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Observability', 'Monitoring'],
    popularityScore: 77,
  },
];

export const teamModules: LearningModule[] = [
  {
    id: 'team-001',
    title: 'React Advanced Patterns (Maria\'s Branch)',
    description: 'Forked version with additional notes on performance optimization',
    type: 'video',
    duration: 45,
    difficulty: 'advanced',
    category: 'Frontend Development',
    mandatory: false,
    progress: 80,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    tags: ['React', 'JavaScript', 'Frontend'],
    createdBy: 'emp-002',
    isBranched: true,
    parentModule: 'mod-001',
    comments: [
      {
        id: 'c-001',
        userId: 'emp-002',
        userName: 'Maria Garcia',
        text: 'Added detailed notes on useMemo and useCallback optimization patterns',
        timestamp: new Date('2024-10-25T10:30:00'),
      },
      {
        id: 'c-002',
        userId: 'emp-003',
        userName: 'James Chen',
        text: 'Great additions! Can you also cover React.memo?',
        timestamp: new Date('2024-10-26T14:20:00'),
      },
    ],
  },
  {
    id: 'team-002',
    title: 'Microservices Testing Strategies',
    description: 'Comprehensive guide to testing microservices - created by the backend team',
    type: 'document',
    duration: 75,
    difficulty: 'advanced',
    category: 'Backend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400',
    tags: ['Testing', 'Microservices', 'Backend'],
    createdBy: 'emp-004',
    comments: [
      {
        id: 'c-003',
        userId: 'emp-004',
        userName: 'Sarah Kim',
        text: 'Covered integration testing, contract testing, and chaos engineering',
        timestamp: new Date('2024-10-28T09:15:00'),
      },
    ],
  },
  {
    id: 'team-003',
    title: 'Design Systems & Component Libraries',
    description: 'Building and maintaining scalable design systems',
    type: 'video',
    duration: 60,
    difficulty: 'intermediate',
    category: 'Frontend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop&crop=entropy',
    tags: ['Design Systems', 'UI/UX', 'Frontend'],
    createdBy: 'emp-005',
    comments: [],
  },
];

export const teamMembers = [
  {
    id: 'emp-001',
    name: 'Alex Rivera',
    position: 'Senior Software Engineer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    completionRate: 78,
    activeModules: 5,
  },
  {
    id: 'emp-002',
    name: 'Maria Garcia',
    position: 'Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    completionRate: 85,
    activeModules: 4,
  },
  {
    id: 'emp-003',
    name: 'James Chen',
    position: 'Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    completionRate: 72,
    activeModules: 6,
  },
  {
    id: 'emp-004',
    name: 'Sarah Kim',
    position: 'Backend Engineer',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
    completionRate: 91,
    activeModules: 3,
  },
  {
    id: 'emp-005',
    name: 'David Johnson',
    position: 'UI/UX Engineer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    completionRate: 68,
    activeModules: 7,
  },
];
