import { LearningModule } from '../App';

export const mockModules: LearningModule[] = [
  {
    id: 'mod-001',
    title: 'React Advanced Patterns',
    description: 'Master advanced React patterns including compound components, render props, and custom hooks',
    type: 'video',
    duration: 45,
    difficulty: 'advanced',
    category: 'Frontend Development',
    mandatory: false,
    progress: 65,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    tags: ['React', 'JavaScript', 'Frontend'],
    createdBy: 'emp-001',
  },
  {
    id: 'mod-002',
    title: 'Security Compliance Training 2024',
    description: 'Annual security and compliance training required for all employees',
    type: 'interactive',
    duration: 30,
    difficulty: 'beginner',
    category: 'Compliance',
    mandatory: true,
    progress: 100,
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400',
    tags: ['Security', 'Compliance', 'Mandatory'],
  },
  {
    id: 'mod-003',
    title: 'Microservices Architecture Deep Dive',
    description: 'Learn how to design, build, and deploy scalable microservices',
    type: 'podcast',
    duration: 60,
    difficulty: 'intermediate',
    category: 'Backend Development',
    mandatory: false,
    progress: 20,
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
    tags: ['Architecture', 'Backend', 'Microservices'],
  },
  {
    id: 'mod-004',
    title: 'Data Privacy & GDPR',
    description: 'Understanding data privacy regulations and GDPR compliance',
    type: 'document',
    duration: 40,
    difficulty: 'beginner',
    category: 'Compliance',
    mandatory: true,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400',
    tags: ['Privacy', 'GDPR', 'Compliance'],
  },
  {
    id: 'mod-005',
    title: 'Leadership Fundamentals',
    description: 'Essential leadership skills for aspiring managers and team leads',
    type: 'video',
    duration: 90,
    difficulty: 'intermediate',
    category: 'Leadership',
    mandatory: false,
    progress: 40,
    thumbnail: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
    tags: ['Leadership', 'Management', 'Soft Skills'],
  },
  {
    id: 'mod-006',
    title: 'TypeScript Mastery',
    description: 'From basics to advanced TypeScript features and patterns',
    type: 'video',
    duration: 120,
    difficulty: 'intermediate',
    category: 'Frontend Development',
    mandatory: false,
    progress: 15,
    thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400',
    tags: ['TypeScript', 'JavaScript', 'Frontend'],
  },
  {
    id: 'mod-007',
    title: 'Agile & Scrum Best Practices',
    description: 'Master agile methodologies and scrum framework',
    type: 'podcast',
    duration: 50,
    difficulty: 'beginner',
    category: 'Project Management',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    tags: ['Agile', 'Scrum', 'Project Management'],
  },
  {
    id: 'mod-008',
    title: 'Cloud Architecture with AWS',
    description: 'Design and implement scalable cloud solutions on AWS',
    type: 'video',
    duration: 180,
    difficulty: 'advanced',
    category: 'Cloud Computing',
    mandatory: false,
    progress: 5,
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    tags: ['AWS', 'Cloud', 'Architecture'],
  },
];

export const teamModules: LearningModule[] = [
  {
    id: 'team-001',
    title: 'React Advanced Patterns (Maria\'s Branch)',
    description: 'Forked version with additional notes on performance optimization',
    type: 'video',
    duration: 45,
    difficulty: 'advanced',
    category: 'Frontend Development',
    mandatory: false,
    progress: 80,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    tags: ['React', 'JavaScript', 'Frontend'],
    createdBy: 'emp-002',
    isBranched: true,
    parentModule: 'mod-001',
    comments: [
      {
        id: 'c-001',
        userId: 'emp-002',
        userName: 'Maria Garcia',
        text: 'Added detailed notes on useMemo and useCallback optimization patterns',
        timestamp: new Date('2024-10-25T10:30:00'),
      },
      {
        id: 'c-002',
        userId: 'emp-003',
        userName: 'James Chen',
        text: 'Great additions! Can you also cover React.memo?',
        timestamp: new Date('2024-10-26T14:20:00'),
      },
    ],
  },
  {
    id: 'team-002',
    title: 'Microservices Testing Strategies',
    description: 'Comprehensive guide to testing microservices - created by the backend team',
    type: 'document',
    duration: 75,
    difficulty: 'advanced',
    category: 'Backend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400',
    tags: ['Testing', 'Microservices', 'Backend'],
    createdBy: 'emp-004',
    comments: [
      {
        id: 'c-003',
        userId: 'emp-004',
        userName: 'Sarah Kim',
        text: 'Covered integration testing, contract testing, and chaos engineering',
        timestamp: new Date('2024-10-28T09:15:00'),
      },
    ],
  },
  {
    id: 'team-003',
    title: 'Design Systems & Component Libraries',
    description: 'Building and maintaining scalable design systems',
    type: 'video',
    duration: 60,
    difficulty: 'intermediate',
    category: 'Frontend Development',
    mandatory: false,
    progress: 0,
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
    tags: ['Design Systems', 'UI/UX', 'Frontend'],
    createdBy: 'emp-005',
    comments: [],
  },
];

export const teamMembers = [
  {
    id: 'emp-001',
    name: 'Alex Rivera',
    position: 'Senior Software Engineer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    completionRate: 78,
    activeModules: 5,
  },
  {
    id: 'emp-002',
    name: 'Maria Garcia',
    position: 'Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    completionRate: 85,
    activeModules: 4,
  },
  {
    id: 'emp-003',
    name: 'James Chen',
    position: 'Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    completionRate: 72,
    activeModules: 6,
  },
  {
    id: 'emp-004',
    name: 'Sarah Kim',
    position: 'Backend Engineer',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
    completionRate: 91,
    activeModules: 3,
  },
  {
    id: 'emp-005',
    name: 'David Johnson',
    position: 'UI/UX Engineer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    completionRate: 68,
    activeModules: 7,
  },
];
